name: Morgan Ervin Creative
favicon: null
layout_spectrum: 0.99811
typography_spectrum: 0.65147
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131313'
    - '#d1c6a8'
    - '#b31b28'
    - '#68767f'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
